[package]
name = "real_c_string"
version = "1.0.0"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"
description = "Generate string parseable in compiled binary"
license = "MIT"

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

[lib]
proc-macro = true
