[package]
name = "real_c_string"
version = "1.0.1"
authors = ["Лач <iam@lach.pw>"]
edition = "2018"
description = "Generate string parseable in compiled binary"
license = "MIT"

[dependencies]
syn = "2"
quote = "1"

[lib]
proc-macro = true
